#ifndef CONTROLCENTER_GLOBAL_H
#define CONTROLCENTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONTROLCENTER_LIBRARY)
#  define CONTROLCENTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONTROLCENTERSHARED_EXPORT
#endif

#endif // CONTROLCENTER_GLOBAL_H
